### ISSUE TITLE
Recursive programs are categorised as "fail".

### ISSUE THREAD

**Issue by Davydzz** [Department-of-Administrative-Affairs/CS259-tests#2]
They should be "PASS // Divergence".

**Comment by s-clerc** [comment]
Hello,

Thank you for the issue, 

These tests were primarily prepared by past years and so there can be some lingering mistakes.

If you want, you can reörganise the tests in the [shell file](https://github.com/Department-of-Administrative-Affairs/CS259-tests/blob/master/testall) to have a separate divergence section.

**Comment by Davydzz** [comment]
ok
